trigger:
  paths:
    include:
      - backend/**
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    cd backend
    dotnet restore
    dotnet build --configuration $(buildConfiguration)
    dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Build and Publish .NET App'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
    artifactName: 'backend'
    publishLocation: 'Container'
